### ISSUE TITLE
An issue in VisiData repo

### ISSUE THREAD

**Issue by aborruso** [jsvine/visidata-cheat-sheet#8]
Hi @jsvine 
what about to open an issue in VisiData repo to announce "officially" this cheat-sheet?

If you agree, I think you should do it, because it's your (great) idea

**Comment by jsvine** [comment]
Thanks, @aborruso! @saulpw is aware of the cheat sheet ... and I'll let him decide whether to link to it in the official documentation. I'll also plan on linking to it from my *An Introduction to VisiData* tutorial.

Or would the idea be to submit an issue so that the repository-"watcher"s get notified?

**Comment by aborruso** [comment]
@jsvine the idea is to submit an issue so that the repository-"watcher"s get notified. But we can wait @saulpw decisions

Thank you
